### ISSUE TITLE
New heroku engine breaks Procfile chain

### ISSUE THREAD

**Issue by ravenium** [szechyjs/kegbot-heroku#8]
I realize there may not be a ton of enthusiasm for triage since the core server app hasn't seen much action in the past year+, but I thought I'd post this anyway :)

Apparently somewhere in the past few weeks our kegbot app crashed.  I figured it was due to the fact that Postmark was turned off, but I was able to finally able to grab a reasonably telling log snippet (see below).  It looks like perhaps Heroku has perhaps deprecated/turned off some foreman features, though for the life of my I can't figure out what.  The 2 Procfile method was a necessary evil to get celery working, I think.

Anyhow, I think I'm pretty dead in the water?  Any ideas, or is it time to just accept that there's only so much that can be done?

```
Jul 16 18:18:40 heroku-app-name heroku/web.1: Starting process with command `env > .env; env GEM_HOME=/app/.ruby-gems env PATH=PATH:/app/.ruby-gems/bin foreman start -f ProcfileFree`
Jul 16 15:24:32 heroku-app-name app/web.1: 22:24:31 celery.1 | unknown command: kegbot run_workers 
Jul 16 15:24:33 heroku-app-name app/web.1: 22:24:32 web.1    | Warning: run_gunicorn is deprecated, call `gunicorn pykeg.web.wsgi:application -b 0.0.0.0:40689` instead. 
Jul 16 15:24:33 heroku-app-name heroku/web.1: State changed from starting to up 
 ul 16 15:25:05 heroku-app-name app/web.1: 22:25:04 web.1    | exited with code 3 
Jul 16 15:25:05 heroku-app-name app/web.1: 22:25:04 system   | sending SIGTERM to all processes 
Jul 16 15:25:05 heroku-app-name app/web.1: /app/.ruby-gems/gems/foreman-0.84.0/lib/foreman/engine.rb:200:in `kill': no implicit conversion from nil to integer (TypeError) 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/foreman-0.84.0/lib/foreman/engine.rb:200:in `kill_children' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/foreman-0.84.0/lib/foreman/engine.rb:472:in `terminate_gracefully' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/foreman-0.84.0/lib/foreman/engine.rb:438:in `wait_for_shutdown_or_child_termination' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/foreman-0.84.0/lib/foreman/engine.rb:60:in `start' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/foreman-0.84.0/lib/foreman/cli.rb:42:in `start' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/thor-0.19.4/lib/thor/command.rb:27:in `run' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/thor-0.19.4/lib/thor/base.rb:444:in `start' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/gems/foreman-0.84.0/bin/foreman:7:in `<top (required)>' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/bin/foreman:23:in `load' 
Jul 16 15:25:05 heroku-app-name app/web.1: 	from /app/.ruby-gems/bin/foreman:23:in `<main>' 
Jul 16 15:25:05 heroku-app-name heroku/web.1: Process exited with status 1 
Jul 16 15:25:05 heroku-app-name heroku/web.1: State changed from up to crashed 
```

**Comment by ravenium** [comment]
A quick update on this - the crash was in part because the app went looking for the env var for postmark and finding none, promptly bailed.  Added a fake one, then it turns out the newest celery doesn't install vine, so added that to requirements (man, I need to remember use to branches for testing, heh).

After that it was something re: LRUcache, which as near as I can tell required a god-awful balance of versioning of the various django-social and foursquare plugins.  Eventually, it just worked.  I have no confidence in the actual stability of the result, but it at least works.

I think at this point we'd have to hope there's more work done on the kegbot-server package.  There are a lot of CVEs (thankfully nothing horribly nasty) on some of the version freezes, and only continued development is going to fix it.

Anyhow, sorry for the soapbox and spam - thanks again for all the hard work in originating this.

**Comment by szechyjs** [comment]
Thanks for the input. I actually started an offline branch that addresses the postmark issue as well as some of the issues with new package versions. @mik3y has started on a new version of kegbot-server, once he releases v1.3 I'll push my update as the changes are lined up with that release.

**Comment by ravenium** [comment]
That's great news - will be happy to help as needed.

**Comment by mik3y** [comment]
Thanks for the heads up Jared!

BTW, if either of you would like to chip in on the 1.3 stuff, do feel free to pull against the branch -- main goal is to "de cruft" some of those awful deps & get things easier to dev on.
